import type { Profile, Session, Checkin, Journey, Integration, Mirror, Entitlement } from './types';

export const MOCK_USER_ID = 'mock-user-001';

export const mockProfile: Profile = {
  id: MOCK_USER_ID,
  preferred_name: 'Kris',
  age_range: '25–34',
  sex: 'Prefer not to say',
  country: 'United States',
  experience_level: 'This is part of my life',
  practices: ['Breathwork'],
  goals: [
    'Nervous system regulation',
    'Emotional release',
    'Understanding my own patterns',
  ],
  vocabulary_framework: 'plain',
  chakra_mapping: true,
  weekly_mirror_reminder: true,
  monthly_mirror_reminder: true,
  onboarding_complete: true,
  created_at: '2026-05-07T10:00:00.000Z',
  updated_at: '2026-05-07T10:00:00.000Z',
};

export const mockSessions: Session[] = [
  { id: 'session-001', user_id: MOCK_USER_ID, practice_type: 'Breathwork', duration_minutes: 45, journey_id: 'journey-001', created_at: '2026-06-01T09:15:00.000Z', updated_at: '2026-06-01T09:15:00.000Z' },
  { id: 'session-002', user_id: MOCK_USER_ID, practice_type: 'Breathwork', duration_minutes: 30, journey_id: null, created_at: '2026-06-08T08:30:00.000Z', updated_at: '2026-06-08T08:30:00.000Z' },
  { id: 'session-003', user_id: MOCK_USER_ID, practice_type: 'Breathwork', duration_minutes: 30, journey_id: null, created_at: '2026-05-16T09:00:00.000Z', updated_at: '2026-05-16T09:00:00.000Z' },
  { id: 'session-004', user_id: MOCK_USER_ID, practice_type: 'Somatic Experiencing', duration_minutes: 45, journey_id: null, created_at: '2026-05-17T10:30:00.000Z', updated_at: '2026-05-17T10:30:00.000Z' },
  { id: 'session-005', user_id: MOCK_USER_ID, practice_type: 'Breathwork', duration_minutes: 60, journey_id: null, created_at: '2026-05-19T08:00:00.000Z', updated_at: '2026-05-19T08:00:00.000Z' },
  { id: 'session-006', user_id: MOCK_USER_ID, practice_type: 'Meditation / Vipassana', duration_minutes: 20, journey_id: null, created_at: '2026-05-20T07:30:00.000Z', updated_at: '2026-05-20T07:30:00.000Z' },
  { id: 'session-007', user_id: MOCK_USER_ID, practice_type: 'Breathwork', duration_minutes: 40, journey_id: null, created_at: '2026-05-22T09:00:00.000Z', updated_at: '2026-05-22T09:00:00.000Z' },
  { id: 'session-008', user_id: MOCK_USER_ID, practice_type: 'Yoga', duration_minutes: 35, journey_id: 'journey-001', created_at: '2026-05-23T08:15:00.000Z', updated_at: '2026-05-23T08:15:00.000Z' },
  { id: 'session-009', user_id: MOCK_USER_ID, practice_type: 'Breathwork', duration_minutes: 30, journey_id: null, created_at: '2026-05-25T09:30:00.000Z', updated_at: '2026-05-25T09:30:00.000Z' },
  { id: 'session-010', user_id: MOCK_USER_ID, practice_type: 'Somatic Experiencing', duration_minutes: 50, journey_id: null, created_at: '2026-05-26T10:00:00.000Z', updated_at: '2026-05-26T10:00:00.000Z' },
  { id: 'session-011', user_id: MOCK_USER_ID, practice_type: 'Breathwork', duration_minutes: 45, journey_id: 'journey-001', created_at: '2026-05-28T08:00:00.000Z', updated_at: '2026-05-28T08:00:00.000Z' },
  { id: 'session-012', user_id: MOCK_USER_ID, practice_type: 'Meditation / Vipassana', duration_minutes: 25, journey_id: null, created_at: '2026-05-29T07:45:00.000Z', updated_at: '2026-05-29T07:45:00.000Z' },
  { id: 'session-013', user_id: MOCK_USER_ID, practice_type: 'Breathwork', duration_minutes: 35, journey_id: null, created_at: '2026-05-31T09:00:00.000Z', updated_at: '2026-05-31T09:00:00.000Z' },
  { id: 'session-014', user_id: MOCK_USER_ID, practice_type: 'Yoga', duration_minutes: 40, journey_id: null, created_at: '2026-06-02T08:30:00.000Z', updated_at: '2026-06-02T08:30:00.000Z' },
  { id: 'session-015', user_id: MOCK_USER_ID, practice_type: 'Breathwork', duration_minutes: 60, journey_id: 'journey-001', created_at: '2026-06-03T09:00:00.000Z', updated_at: '2026-06-03T09:00:00.000Z' },
  { id: 'session-016', user_id: MOCK_USER_ID, practice_type: 'Somatic Experiencing', duration_minutes: 35, journey_id: null, created_at: '2026-06-04T10:15:00.000Z', updated_at: '2026-06-04T10:15:00.000Z' },
  { id: 'session-017', user_id: MOCK_USER_ID, practice_type: 'Breathwork', duration_minutes: 25, journey_id: null, created_at: '2026-06-05T08:00:00.000Z', updated_at: '2026-06-05T08:00:00.000Z' },
  { id: 'session-018', user_id: MOCK_USER_ID, practice_type: 'Breathwork', duration_minutes: 50, journey_id: 'journey-001', created_at: '2026-06-07T09:00:00.000Z', updated_at: '2026-06-07T09:00:00.000Z' },
  { id: 'session-019', user_id: MOCK_USER_ID, practice_type: 'Meditation / Vipassana', duration_minutes: 20, journey_id: 'journey-002', created_at: '2026-06-09T07:30:00.000Z', updated_at: '2026-06-09T07:30:00.000Z' },
  { id: 'session-020', user_id: MOCK_USER_ID, practice_type: 'Breathwork', duration_minutes: 45, journey_id: null, created_at: '2026-06-10T09:00:00.000Z', updated_at: '2026-06-10T09:00:00.000Z' },
  { id: 'session-021', user_id: MOCK_USER_ID, practice_type: 'Yoga', duration_minutes: 30, journey_id: 'journey-002', created_at: '2026-06-11T08:15:00.000Z', updated_at: '2026-06-11T08:15:00.000Z' },
  { id: 'session-022', user_id: MOCK_USER_ID, practice_type: 'Breathwork', duration_minutes: null, journey_id: null, created_at: '2026-06-14T09:00:00.000Z', updated_at: '2026-06-14T09:00:00.000Z' },
];

export const mockCheckins: Checkin[] = [
  {
    id: 'checkin-001', user_id: MOCK_USER_ID, session_id: 'session-001',
    nervous_system_state: 'shutdown', energetic_shift: 'Something released', release_qualities: ['tears', 'shaking/trembling'],
    emotion_tags: ['grief', 'sadness', 'release'],
    body_sensations: [{ region: 'chest', quality: 'heaviness' }, { region: 'throat', quality: 'releasing' }, { region: 'eyes', quality: 'tears' }],
    connection_type: 'tied_to_something', connection_note: 'My father',
    elaboration_note: "Something moved in the chest today. Didn't expect it but the grief was there, just under the surface. Throat opened about 20 minutes in — that lump finally let go.",
    difference_note: null, created_at: '2026-06-01T09:15:00.000Z', updated_at: '2026-06-01T09:15:00.000Z',
  },
  {
    id: 'checkin-002', user_id: MOCK_USER_ID, session_id: 'session-002',
    nervous_system_state: 'grounded', energetic_shift: 'Something shifted', release_qualities: ['heat/cold wave'],
    emotion_tags: ['grief', 'warmth', 'relief'],
    body_sensations: [{ region: 'chest', quality: 'opening' }, { region: 'throat', quality: 'warmth' }, { region: 'solar_plexus', quality: 'expansion' }],
    connection_type: 'pure_sensation', connection_note: null,
    elaboration_note: 'Lighter today. The grief was still present but felt more like it was moving than stuck. Heat in the chest moving up through the throat. Something is shifting.',
    difference_note: 'Less constriction in the throat. Last time it felt blocked — today it opened.',
    created_at: '2026-06-08T08:30:00.000Z', updated_at: '2026-06-08T08:30:00.000Z',
  },
  {
    id: 'checkin-003', user_id: MOCK_USER_ID, session_id: 'session-003',
    nervous_system_state: 'grounded', energetic_shift: 'Something shifted', release_qualities: [],
    emotion_tags: ['joy', 'gratitude', 'love'],
    body_sensations: [{ region: 'chest', quality: 'warmth' }, { region: 'throat', quality: 'opening' }],
    connection_type: 'pure_sensation', connection_note: null, elaboration_note: 'Clear and open. Warmth in the chest throughout.', difference_note: null,
    created_at: '2026-05-16T09:00:00.000Z', updated_at: '2026-05-16T09:00:00.000Z',
  },
  {
    id: 'checkin-004', user_id: MOCK_USER_ID, session_id: 'session-004',
    nervous_system_state: 'activated', energetic_shift: 'Nothing moved', release_qualities: ['shaking/trembling'],
    emotion_tags: ['fear', 'anxiety'],
    body_sensations: [{ region: 'solar_plexus', quality: 'churning' }, { region: 'chest', quality: 'tightness' }],
    connection_type: 'tied_to_something', connection_note: 'Work pressure', elaboration_note: 'System was running hot the whole session. Hard to settle.', difference_note: null,
    created_at: '2026-05-17T10:30:00.000Z', updated_at: '2026-05-17T10:30:00.000Z',
  },
  {
    id: 'checkin-005', user_id: MOCK_USER_ID, session_id: 'session-005',
    nervous_system_state: 'shutdown', energetic_shift: 'Something released', release_qualities: ['tears', 'sighing'],
    emotion_tags: ['grief', 'sadness', 'longing'],
    body_sensations: [{ region: 'chest', quality: 'heaviness' }, { region: 'throat', quality: 'lump' }, { region: 'eyes', quality: 'tears' }],
    connection_type: 'tied_to_something', connection_note: 'Childhood memory',
    elaboration_note: 'Heavy from the start. Grief came in waves — chest, then throat. Did not try to move it. Just let it be.',
    difference_note: null, created_at: '2026-05-19T08:00:00.000Z', updated_at: '2026-05-19T08:00:00.000Z',
  },
  {
    id: 'checkin-006', user_id: MOCK_USER_ID, session_id: 'session-006',
    nervous_system_state: 'grounded', energetic_shift: 'Something shifted', release_qualities: [],
    emotion_tags: ['relief', 'openness'],
    body_sensations: [{ region: 'chest', quality: 'softening' }, { region: 'spine', quality: 'warmth' }],
    connection_type: 'pure_sensation', connection_note: null, elaboration_note: 'Quiet session. Body felt lighter.', difference_note: null,
    created_at: '2026-05-20T07:30:00.000Z', updated_at: '2026-05-20T07:30:00.000Z',
  },
  {
    id: 'checkin-007', user_id: MOCK_USER_ID, session_id: 'session-007',
    nervous_system_state: 'activated', energetic_shift: 'Nothing moved', release_qualities: ['heat/cold wave'],
    emotion_tags: ['anger', 'frustration', 'resentment'],
    body_sensations: [{ region: 'solar_plexus', quality: 'burning' }, { region: 'arms', quality: 'tension' }],
    connection_type: 'tied_to_something', connection_note: 'Old boundary violation',
    elaboration_note: 'Anger moved through the solar plexus. Strong activation. Stayed with it.', difference_note: null,
    created_at: '2026-05-22T09:00:00.000Z', updated_at: '2026-05-22T09:00:00.000Z',
  },
  {
    id: 'checkin-008', user_id: MOCK_USER_ID, session_id: 'session-008',
    nervous_system_state: 'shutdown', energetic_shift: 'Something released', release_qualities: ['tears', 'sighing'],
    emotion_tags: ['grief', 'sadness', 'longing'],
    body_sensations: [{ region: 'chest', quality: 'heaviness' }, { region: 'throat', quality: 'constriction' }, { region: 'spine', quality: 'sinking' }],
    connection_type: 'tied_to_something', connection_note: 'Absence of someone',
    elaboration_note: 'Grief sat heavy today. The yoga postures seemed to hold it in the body — spine, chest, throat all together.',
    difference_note: null, created_at: '2026-05-23T08:15:00.000Z', updated_at: '2026-05-23T08:15:00.000Z',
  },
  {
    id: 'checkin-009', user_id: MOCK_USER_ID, session_id: 'session-009',
    nervous_system_state: 'grounded', energetic_shift: 'Something shifted', release_qualities: [],
    emotion_tags: ['love', 'warmth', 'gratitude'],
    body_sensations: [{ region: 'chest', quality: 'warmth' }, { region: 'throat', quality: 'opening' }],
    connection_type: 'pure_sensation', connection_note: null, elaboration_note: 'Soft and full. Warmth in the chest. No agenda.', difference_note: null,
    created_at: '2026-05-25T09:30:00.000Z', updated_at: '2026-05-25T09:30:00.000Z',
  },
  {
    id: 'checkin-010', user_id: MOCK_USER_ID, session_id: 'session-010',
    nervous_system_state: 'activated', energetic_shift: 'Nothing moved', release_qualities: ['shaking/trembling'],
    emotion_tags: ['anxiety', 'fear', 'dread'],
    body_sensations: [{ region: 'solar_plexus', quality: 'churning' }, { region: 'pelvis', quality: 'tightness' }],
    connection_type: 'tied_to_something', connection_note: 'Upcoming life change',
    elaboration_note: 'System activated. Fear was underneath the anxiety — took most of the session to name it.', difference_note: null,
    created_at: '2026-05-26T10:00:00.000Z', updated_at: '2026-05-26T10:00:00.000Z',
  },
  {
    id: 'checkin-011', user_id: MOCK_USER_ID, session_id: 'session-011',
    nervous_system_state: 'shutdown', energetic_shift: 'Something released', release_qualities: ['sighing', 'yawning'],
    emotion_tags: ['shame', 'grief', 'smallness'],
    body_sensations: [{ region: 'throat', quality: 'constriction' }, { region: 'chest', quality: 'heaviness' }, { region: 'solar_plexus', quality: 'sinking' }],
    connection_type: 'tied_to_something', connection_note: 'Early shame memory',
    elaboration_note: 'Shame and grief together. Hard to separate them. The throat locked early. Stayed in the shutdown place.',
    difference_note: null, created_at: '2026-05-28T08:00:00.000Z', updated_at: '2026-05-28T08:00:00.000Z',
  },
  {
    id: 'checkin-012', user_id: MOCK_USER_ID, session_id: 'session-012',
    nervous_system_state: 'grounded', energetic_shift: 'Something shifted', release_qualities: ['heat/cold wave'],
    emotion_tags: ['release', 'relief', 'openness'],
    body_sensations: [{ region: 'chest', quality: 'opening' }, { region: 'solar_plexus', quality: 'expansion' }],
    connection_type: 'pure_sensation', connection_note: null, elaboration_note: 'Something released. Chest opened. Felt present.', difference_note: 'Less tightness in the solar plexus than last week.',
    created_at: '2026-05-29T07:45:00.000Z', updated_at: '2026-05-29T07:45:00.000Z',
  },
  {
    id: 'checkin-013', user_id: MOCK_USER_ID, session_id: 'session-013',
    nervous_system_state: 'activated', energetic_shift: 'Nothing moved', release_qualities: [],
    emotion_tags: ['frustration', 'anger'],
    body_sensations: [{ region: 'solar_plexus', quality: 'pressure' }, { region: 'chest', quality: 'tightness' }],
    connection_type: 'tied_to_something', connection_note: 'Relationship difficulty', elaboration_note: 'Activation without much release. The anger felt stuck mid-session.', difference_note: null,
    created_at: '2026-05-31T09:00:00.000Z', updated_at: '2026-05-31T09:00:00.000Z',
  },
  {
    id: 'checkin-014', user_id: MOCK_USER_ID, session_id: 'session-014',
    nervous_system_state: 'grounded', energetic_shift: 'Something shifted', release_qualities: [],
    emotion_tags: ['gratitude', 'joy', 'warmth'],
    body_sensations: [{ region: 'chest', quality: 'warmth' }, { region: 'throat', quality: 'opening' }, { region: 'spine', quality: 'grounding' }],
    connection_type: 'pure_sensation', connection_note: null, elaboration_note: 'Full, grounded, grateful. One of those sessions where it all lands.', difference_note: null,
    created_at: '2026-06-02T08:30:00.000Z', updated_at: '2026-06-02T08:30:00.000Z',
  },
  {
    id: 'checkin-015', user_id: MOCK_USER_ID, session_id: 'session-015',
    nervous_system_state: 'shutdown', energetic_shift: 'Something released', release_qualities: ['tears'],
    emotion_tags: ['grief', 'sadness', 'longing'],
    body_sensations: [{ region: 'chest', quality: 'heaviness' }, { region: 'throat', quality: 'lump' }, { region: 'eyes', quality: 'tears' }],
    connection_type: 'tied_to_something', connection_note: 'My father',
    elaboration_note: 'Same grief. It comes back. Not the same though — it feels more like a presence than an absence now.',
    difference_note: null, created_at: '2026-06-03T09:00:00.000Z', updated_at: '2026-06-03T09:00:00.000Z',
  },
  {
    id: 'checkin-016', user_id: MOCK_USER_ID, session_id: 'session-016',
    nervous_system_state: 'activated', energetic_shift: 'Nothing moved', release_qualities: ['shaking/trembling'],
    emotion_tags: ['anger', 'fear', 'frustration'],
    body_sensations: [{ region: 'solar_plexus', quality: 'burning' }, { region: 'chest', quality: 'tightness' }],
    connection_type: 'tied_to_something', connection_note: 'Pattern recognition',
    elaboration_note: 'The anger is a cover for fear. Seeing the pattern more clearly. Both in the solar plexus.', difference_note: null,
    created_at: '2026-06-04T10:15:00.000Z', updated_at: '2026-06-04T10:15:00.000Z',
  },
  {
    id: 'checkin-017', user_id: MOCK_USER_ID, session_id: 'session-017',
    nervous_system_state: 'grounded', energetic_shift: 'Something shifted', release_qualities: [],
    emotion_tags: ['warmth', 'love', 'relief'],
    body_sensations: [{ region: 'chest', quality: 'warmth' }, { region: 'throat', quality: 'softening' }],
    connection_type: 'pure_sensation', connection_note: null, elaboration_note: 'Warmth moved through quickly. Short session but complete.', difference_note: null,
    created_at: '2026-06-05T08:00:00.000Z', updated_at: '2026-06-05T08:00:00.000Z',
  },
  {
    id: 'checkin-018', user_id: MOCK_USER_ID, session_id: 'session-018',
    nervous_system_state: 'shutdown', energetic_shift: 'Something released', release_qualities: ['tears', 'sighing'],
    emotion_tags: ['grief', 'numbness', 'emptiness'],
    body_sensations: [{ region: 'chest', quality: 'heaviness' }, { region: 'throat', quality: 'constriction' }, { region: 'eyes', quality: 'tears' }],
    connection_type: 'tied_to_something', connection_note: 'My father',
    elaboration_note: 'Grief and numbness alternating. The numbness feels protective. Stayed with both.',
    difference_note: null, created_at: '2026-06-07T09:00:00.000Z', updated_at: '2026-06-07T09:00:00.000Z',
  },
  {
    id: 'checkin-019', user_id: MOCK_USER_ID, session_id: 'session-019',
    nervous_system_state: 'grounded', energetic_shift: 'Something shifted', release_qualities: [],
    emotion_tags: ['joy', 'gratitude'],
    body_sensations: [{ region: 'chest', quality: 'warmth' }, { region: 'spine', quality: 'grounding' }],
    connection_type: 'pure_sensation', connection_note: null, elaboration_note: 'Quiet presence. Just being.', difference_note: null,
    created_at: '2026-06-09T07:30:00.000Z', updated_at: '2026-06-09T07:30:00.000Z',
  },
  {
    id: 'checkin-020', user_id: MOCK_USER_ID, session_id: 'session-020',
    nervous_system_state: 'activated', energetic_shift: 'Nothing moved', release_qualities: ['shaking/trembling'],
    emotion_tags: ['fear', 'anxiety', 'dread'],
    body_sensations: [{ region: 'solar_plexus', quality: 'churning' }, { region: 'chest', quality: 'tightness' }, { region: 'arms', quality: 'tension' }],
    connection_type: 'tied_to_something', connection_note: 'Uncertainty about the future',
    elaboration_note: 'Strong activation through the whole session. Fear is loud right now.', difference_note: null,
    created_at: '2026-06-10T09:00:00.000Z', updated_at: '2026-06-10T09:00:00.000Z',
  },
  {
    id: 'checkin-021', user_id: MOCK_USER_ID, session_id: 'session-021',
    nervous_system_state: 'grounded', energetic_shift: 'Something shifted', release_qualities: [],
    emotion_tags: ['relief', 'openness', 'warmth'],
    body_sensations: [{ region: 'chest', quality: 'opening' }, { region: 'throat', quality: 'warmth' }, { region: 'full_body', quality: 'grounding' }],
    connection_type: 'pure_sensation', connection_note: null, elaboration_note: 'Full body ease. The yoga held something that breathwork cannot.', difference_note: 'More embodied than usual.',
    created_at: '2026-06-11T08:15:00.000Z', updated_at: '2026-06-11T08:15:00.000Z',
  },
  {
    id: 'checkin-022', user_id: MOCK_USER_ID, session_id: 'session-022',
    nervous_system_state: 'shutdown', energetic_shift: 'Something released', release_qualities: ['sighing', 'yawning'],
    emotion_tags: ['grief', 'sadness'],
    body_sensations: [{ region: 'chest', quality: 'heaviness' }, { region: 'throat', quality: 'lump' }],
    connection_type: 'tied_to_something', connection_note: 'My father',
    elaboration_note: 'Grief again. It feels different — older somehow. Not fresh. Almost like a memory of itself.',
    difference_note: null, created_at: '2026-06-14T09:00:00.000Z', updated_at: '2026-06-14T09:00:00.000Z',
  },
];

export const mockJourneys: Journey[] = [
  {
    id: 'journey-001',
    user_id: MOCK_USER_ID,
    name: 'Grief and release',
    start_date: '2026-05-21',
    duration_days: 30,
    intentions: ['Grief processing', 'Emotional release', 'Nervous system regulation'],
    status: 'active',
    created_at: '2026-05-21T09:00:00.000Z',
    closed_at: null,
  },
  {
    id: 'journey-002',
    user_id: MOCK_USER_ID,
    name: 'Presence practice',
    start_date: '2026-06-07',
    duration_days: 21,
    intentions: ['Presence', 'Self-trust'],
    status: 'active',
    created_at: '2026-06-07T09:00:00.000Z',
    closed_at: null,
  },
];

export const mockIntegrations: Integration[] = [
  { id: 'integ-001', user_id: MOCK_USER_ID, journey_id: null, note_date: '2026-05-19', category: 'Emotions', triggers_q1: null, triggers_q2: null, triggers_q3: null, memories_q1: null, memories_q2: null, memories_q3: null, emotions_q1: 'Grief came in waves. Still feeling it hours later.', emotions_q2: null, emotions_q3: null, body_q1: null, body_q2: null, body_q3: null, patterns_q1: null, patterns_q2: null, patterns_q3: null, meaning_q1: null, meaning_q2: null, meaning_q3: null, realizations_q1: null, realizations_q2: null, realizations_q3: null, actions_q1: null, actions_q2: null, actions_q3: null, gratitude_q1: null, gratitude_q2: null, gratitude_q3: null, free_text: null, created_at: '2026-05-19T12:00:00.000Z', updated_at: '2026-05-19T12:00:00.000Z' },
  { id: 'integ-002', user_id: MOCK_USER_ID, journey_id: null, note_date: '2026-05-20', category: 'Emotions', triggers_q1: null, triggers_q2: null, triggers_q3: null, memories_q1: null, memories_q2: null, memories_q3: null, emotions_q1: 'Relief feels unfamiliar. Sitting with that.', emotions_q2: null, emotions_q3: null, body_q1: null, body_q2: null, body_q3: null, patterns_q1: null, patterns_q2: null, patterns_q3: null, meaning_q1: null, meaning_q2: null, meaning_q3: null, realizations_q1: null, realizations_q2: null, realizations_q3: null, actions_q1: null, actions_q2: null, actions_q3: null, gratitude_q1: null, gratitude_q2: null, gratitude_q3: null, free_text: null, created_at: '2026-05-20T11:30:00.000Z', updated_at: '2026-05-20T11:30:00.000Z' },
  { id: 'integ-003', user_id: MOCK_USER_ID, journey_id: 'journey-001', note_date: '2026-05-23', category: 'Body', triggers_q1: null, triggers_q2: null, triggers_q3: null, memories_q1: null, memories_q2: null, memories_q3: null, emotions_q1: null, emotions_q2: null, emotions_q3: null, body_q1: 'The spine held something today. Still feeling it between the shoulder blades.', body_q2: null, body_q3: null, patterns_q1: null, patterns_q2: null, patterns_q3: null, meaning_q1: null, meaning_q2: null, meaning_q3: null, realizations_q1: null, realizations_q2: null, realizations_q3: null, actions_q1: null, actions_q2: null, actions_q3: null, gratitude_q1: null, gratitude_q2: null, gratitude_q3: null, free_text: null, created_at: '2026-05-23T14:00:00.000Z', updated_at: '2026-05-23T14:00:00.000Z' },
  { id: 'integ-004', user_id: MOCK_USER_ID, journey_id: null, note_date: '2026-05-26', category: 'Triggers', triggers_q1: 'The fear came from a specific image — being left alone with no path forward.', triggers_q2: null, triggers_q3: null, memories_q1: null, memories_q2: null, memories_q3: null, emotions_q1: null, emotions_q2: null, emotions_q3: null, body_q1: null, body_q2: null, body_q3: null, patterns_q1: null, patterns_q2: null, patterns_q3: null, meaning_q1: null, meaning_q2: null, meaning_q3: null, realizations_q1: null, realizations_q2: null, realizations_q3: null, actions_q1: null, actions_q2: null, actions_q3: null, gratitude_q1: null, gratitude_q2: null, gratitude_q3: null, free_text: null, created_at: '2026-05-26T13:00:00.000Z', updated_at: '2026-05-26T13:00:00.000Z' },
  { id: 'integ-005', user_id: MOCK_USER_ID, journey_id: null, note_date: '2026-05-29', category: 'Patterns', triggers_q1: null, triggers_q2: null, triggers_q3: null, memories_q1: null, memories_q2: null, memories_q3: null, emotions_q1: null, emotions_q2: null, emotions_q3: null, body_q1: null, body_q2: null, body_q3: null, patterns_q1: 'Release always starts in the solar plexus, then moves up. Every time.', patterns_q2: null, patterns_q3: null, meaning_q1: null, meaning_q2: null, meaning_q3: null, realizations_q1: null, realizations_q2: null, realizations_q3: null, actions_q1: null, actions_q2: null, actions_q3: null, gratitude_q1: null, gratitude_q2: null, gratitude_q3: null, free_text: null, created_at: '2026-05-29T10:00:00.000Z', updated_at: '2026-05-29T10:00:00.000Z' },
  { id: 'integ-006', user_id: MOCK_USER_ID, journey_id: null, note_date: '2026-06-02', category: 'Gratitude', triggers_q1: null, triggers_q2: null, triggers_q3: null, memories_q1: null, memories_q2: null, memories_q3: null, emotions_q1: null, emotions_q2: null, emotions_q3: null, body_q1: null, body_q2: null, body_q3: null, patterns_q1: null, patterns_q2: null, patterns_q3: null, meaning_q1: null, meaning_q2: null, meaning_q3: null, realizations_q1: null, realizations_q2: null, realizations_q3: null, actions_q1: null, actions_q2: null, actions_q3: null, gratitude_q1: 'Grateful for this body and what it carries and releases.', gratitude_q2: null, gratitude_q3: null, free_text: null, created_at: '2026-06-02T12:00:00.000Z', updated_at: '2026-06-02T12:00:00.000Z' },
  { id: 'integ-007', user_id: MOCK_USER_ID, journey_id: null, note_date: '2026-06-04', category: 'Triggers', triggers_q1: 'The anger and fear live in the same place. Have always been linked.', triggers_q2: null, triggers_q3: null, memories_q1: null, memories_q2: null, memories_q3: null, emotions_q1: null, emotions_q2: null, emotions_q3: null, body_q1: null, body_q2: null, body_q3: null, patterns_q1: null, patterns_q2: null, patterns_q3: null, meaning_q1: null, meaning_q2: null, meaning_q3: null, realizations_q1: null, realizations_q2: null, realizations_q3: null, actions_q1: null, actions_q2: null, actions_q3: null, gratitude_q1: null, gratitude_q2: null, gratitude_q3: null, free_text: null, created_at: '2026-06-04T13:00:00.000Z', updated_at: '2026-06-04T13:00:00.000Z' },
  { id: 'integ-008', user_id: MOCK_USER_ID, journey_id: 'journey-001', note_date: '2026-06-07', category: 'Emotions', triggers_q1: null, triggers_q2: null, triggers_q3: null, memories_q1: null, memories_q2: null, memories_q3: null, emotions_q1: 'Numbness as protection — I can see that now. The grief is underneath, not gone.', emotions_q2: null, emotions_q3: null, body_q1: null, body_q2: null, body_q3: null, patterns_q1: null, patterns_q2: null, patterns_q3: null, meaning_q1: null, meaning_q2: null, meaning_q3: null, realizations_q1: null, realizations_q2: null, realizations_q3: null, actions_q1: null, actions_q2: null, actions_q3: null, gratitude_q1: null, gratitude_q2: null, gratitude_q3: null, free_text: null, created_at: '2026-06-07T13:00:00.000Z', updated_at: '2026-06-07T13:00:00.000Z' },
  { id: 'integ-009', user_id: MOCK_USER_ID, journey_id: null, note_date: '2026-06-10', category: 'Body', triggers_q1: null, triggers_q2: null, triggers_q3: null, memories_q1: null, memories_q2: null, memories_q3: null, emotions_q1: null, emotions_q2: null, emotions_q3: null, body_q1: 'The fear lives in the solar plexus and radiates into the arms. Noticing this more clearly.', body_q2: null, body_q3: null, patterns_q1: null, patterns_q2: null, patterns_q3: null, meaning_q1: null, meaning_q2: null, meaning_q3: null, realizations_q1: null, realizations_q2: null, realizations_q3: null, actions_q1: null, actions_q2: null, actions_q3: null, gratitude_q1: null, gratitude_q2: null, gratitude_q3: null, free_text: null, created_at: '2026-06-10T12:00:00.000Z', updated_at: '2026-06-10T12:00:00.000Z' },
  { id: 'integ-010', user_id: MOCK_USER_ID, journey_id: null, note_date: '2026-06-14', category: 'Meaning', triggers_q1: null, triggers_q2: null, triggers_q3: null, memories_q1: null, memories_q2: null, memories_q3: null, emotions_q1: null, emotions_q2: null, emotions_q3: null, body_q1: null, body_q2: null, body_q3: null, patterns_q1: null, patterns_q2: null, patterns_q3: null, meaning_q1: 'The grief is becoming a companion. Not something to fix. Something to know.', meaning_q2: null, meaning_q3: null, realizations_q1: null, realizations_q2: null, realizations_q3: null, actions_q1: null, actions_q2: null, actions_q3: null, gratitude_q1: null, gratitude_q2: null, gratitude_q3: null, free_text: null, created_at: '2026-06-14T12:00:00.000Z', updated_at: '2026-06-14T12:00:00.000Z' },
];

export const mockMirrors: Mirror[] = [
  {
    id: 'mirror-001',
    type: 'monthly',
    period_start: '2026-05-16',
    period_end: '2026-06-06',
    generated_at: '2026-06-07T20:00:00.000Z',
    content:
      'Across this period, the nervous system spent most of its time moving between activation and shutdown in the first two weeks, then grounded more often in the second half. Grief was the dominant charge, appearing in just over half of all sessions, most often alongside throat and chest activation. Integration notes clustered in the days following longer sessions, frequently circling back to the same family memory. By the final week, body sensations had shifted from heaviness in the chest to warmth and openness in the same region — a notable change from where the month began.',
    summary: 'Grief was the dominant charge, most often alongside throat and chest activation.',
    session_count: 14,
    integration_count: 9,
    status: 'ready',
  },
  {
    id: 'mirror-002',
    type: 'weekly',
    period_start: '2026-06-08',
    period_end: '2026-06-14',
    generated_at: '2026-06-14T20:00:00.000Z',
    content:
      'This week, grief appeared in three of five sessions, most often alongside throat activation and a shutdown nervous system state. Integration notes from Tuesday and Thursday both circled back to the same memory of a parent. By Sunday something shifted — the state moved to grounded and the body sensations moved from chest heaviness to warmth. The pattern across the week suggests something completing rather than repeating.',
    summary: 'Grief appeared in three of five sessions, most often alongside throat activation.',
    session_count: 5,
    integration_count: 4,
    status: 'ready',
  },
];

export const mockEntitlement: Entitlement = {
  id: 'entitlement-dev',
  user_id: MOCK_USER_ID,
  email: 'dev@sinne.app',
  plan: 'mirror_monthly',
  status: 'active',
  current_period_end: '2099-12-31T23:59:59.000Z',
  subscription_id: 'dev-sub-001',
  updated_at: '2026-05-07T10:00:00.000Z',
};